name: Scan level ranking

on:
  schedule:
    - cron: "13 5 * * *"   # einmal täglich um 05:13 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monitor script for ranking
        run: python monitor.py --source ranking

      - name: Commit and push updated state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/state.json
          git commit -m "Update state ranking" || echo "Nichts zu committen"
          git push https://${{ github.token }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }} || true
