# .github/workflows/scan-website.yml
name: Scan website
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python monitor.py --source online
      - name: Commit state
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/state.json
          git commit -m "Update state website" || echo "nichts zu committen"
          git push || true
